### ISSUE TITLE
Invisible link on blue background

### ISSUE THREAD

**Issue by foo-cs** [hemisemidemipresent/color#2]
![image](https://user-images.githubusercontent.com/79788038/157034521-b666b8ae-3ea8-459d-adc7-5c7317efb85e.png)

When background is blue, I can't see my sauce

**Comment by hemisemidemipresent** [comment]
resolved with commit [728d7b5](https://github.com/hemisemidemipresent/color/commit/728d7b5357a08687da8c1aa21494f2f94760d3c5)
